name: project_video
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0

  flutter_localizations:
    sdk: flutter
    

  shared_preferences: ^2.0.15

  equatable: 2.0.3
  flutter_bloc: ^8.0.1

  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
    
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  flutter_html: ^2.2.1

  cupertino_icons: ^1.0.2

  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^1.5.2

  build_runner: ^2.1.10
  json_serializable: ^6.2.0

  
  dart_style: ^2.2.3

  
  flutter_lints: ^1.0.0

  flutter_launcher_icons: 0.9.2

flutter_icons:
  # for ios
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  # for android
  android: true
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#100454"
  # flutter pub run flutter_launcher_icons:main

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #       - asset: assets/fonts/OpenSans-Bold.ttf
  #         weight: 700
   
  #   - family: Quicksand
  #     fonts:
  #       - asset: assets/fonts/Quicksand-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Quicksand-Light.ttf
  #       - asset: assets/fonts/Quicksand-Medium.ttf
  #       - asset: assets/fonts/Quicksand-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
